# permissions for end users to view zachsapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zachsapi-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-project-zachsapi
    app.kubernetes.io/part-of: kubebuilder-project-zachsapi
    app.kubernetes.io/managed-by: kustomize
  name: zachsapi-viewer-role
rules:
- apiGroups:
  - example-crd.com.example-crd.com
  resources:
  - zachsapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example-crd.com.example-crd.com
  resources:
  - zachsapis/status
  verbs:
  - get
