apiVersion: example-crd.com.example-crd.com/v1
kind: ZachsAPI
metadata:
  labels:
    app.kubernetes.io/name: zachsapi
    app.kubernetes.io/instance: zachsapi-sample
    app.kubernetes.io/part-of: kubebuilder-project-zachsapi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-project-zachsapi
  name: zachsapi-sample
spec:
  # TODO(user): Add fields here
